language: java
jdk:
  - oraclejdk8
dist: trusty
branches:
  only:
    - master
    - dev
notifications:
  email:
    recipients:
      - d.rubio@outlook.com
services:
  - mongodb

before_install:
  - chmod +x mvnw
script:
  # Test
  - mvn -Dtest=**/*Test test
  # Integration Test
  - if [ $TRAVIS_TEST_RESULT == 0 ];
    then  mvn -Dtest=**/*IT package;
    else  echo "ERRORES!!! ... se abortan resto de test";
    fi
  # Functional Testing
  - if [ $TRAVIS_TEST_RESULT == 0 ];
    then  mvn -Dtest=**/*FunctionalTesting verify;
    else  echo "ERRORES!!! ... se abortan resto de test";
    fi
