language: java

jdk:
  - oraclejdk8

dist: trusty

branches:
  only:
    - master
    - "/^release-[0-999].[0-999]$/"
    - develop

notifications:
  email:
    recipients:
      - d.rubio@outlook.com

script:
  - mvn -Dtest=**/*Test test
  - if [ $TRAVIS_TEST_RESULT == 0 ]; then  mvn -Dtest=**/*IT package; else  echo "ERRORES!!!
    ... se abortan resto de test"; fi
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=daniel-nx -Dsonar.login=$SONAR

deploy:
  provider: heroku
  on:
    branch: develop
  app: nx-ese-mongo
  api_key:
    secure: R+OwIhrAbY3BSYLRsKd1zaGlOpHZgYx/y6WbpCkvDvVDpmQqlI6RnN1DdvwZLOK2Wgc6keHaAk4f35JrdNRbHvI26amwV/cjyaqj6dTwnQ4C+jnwAH9dW42CCLihmWhbdaMt0tOuN3kEClagILw0SdL5/h5PocFGXUIVAHv2pd8MKm1HhAqTyZkWaIFQu8HtNGlio4xKrvSmzxsiWxeHELvHUwxBJyfizU2g74ywnKLDoCAgPGM1tF+g9X3MypeTbZ2APPiYVs7K2r3P6Q0ZIOC70yRqHaIM/9PavF+QUzl8TshzMh5HeWjEucw3u9DZhDVRiGt5U4MtUVx/Ueas0J758p/5gbKgbYdrvIzKr2+Tp3pFZHm5ydBH3EJ09Zo0dvDwWDmiRsE7SZ4STug6MYpDBkQgmJnjXiV1PfzZUlrmX+3Szv+6EIkuPdBzqeiAWtFobgO0AuldsOPFKwRCUxewze2bjdyFBP4geYkUhHZGf7yC8h3syW6jw9nfqyggH7Nm5vldisAAmxLW77asRRn5ZpingQDkpoOdGiuYHIt6vGqvWda89ZH2Kn6rQStX7HtUYPUL4d9kVKV7Y9YMHtVgnmxGleHzM5BN5szJ9uJaXLil07k9MIYfosLFcGhW5MAkvAo0MFR6oU5U8Pc2Gq7Spl52oRbOJWC5Buja1G8=

  env:
    MONGODB_URI:
    - secure: f3c9i2xurHCTv4EWS5ND4swRu3TcdED+fXgP/Z5q/sEb1ns6NymH5hZrYTtoeuEGkWfY1rj33RkzP8zlB/zIXV19EbHgm9F4bsFAMTa7RVEPNOfb3Nsd0EuKZE8YeVftRqcSo3/WDmM3QW0Htfbf5ZwzlW0R7ivQM0/WMtZfrWtVBqgYki7Rgs7PiJU5O2OjrxDrxnsIS7vlGpiy+QbUjRqo9mFtq24CGXDvySPjbtOg8fSro7f8FLNE5NdcvfPuCaY5DBTdJDhZ7Py9ehXGBTIzcrEmKVTjkRh8RnC0C83/cy1pDyVPJqRjyjwyROk87IizZ6gtarVpswJOCePOF1xVyZ8aTr2XMY6zZKbqj3zuOmAdUn2O1j0UXi5yGx9EFU3iLtNUsboPycDCC+lnmkOs4fnavnlfNEDbIzfFH3exKomSAS+JJYpu4/Ut/29Rb9YfUxomTrL44OyVOrvaVi3boptPLmb2vqUbBk/d2evDFekQkGNTjaI21ieVjb2209J7iDEepnC8dBOoGH4+0GVijFV2k7FwkuXsos50LXBXRBGyHKgnfLQO5bRX743tCMS9LhnK3M07tzgcFau+AafERBgHGQq1kvFOloz/+CPmaxNgmNaCPLcuTlFskyC0EJLV5z1IycxgsWL2mnzLX/bb/aHU1mJO5ARZ2Nn0mBE=

