language: java
jdk:
  - oraclejdk8
dist: trusty
branches:
  only:
    - master
    - "/^release-[0-999].[0-999]$/"
    - dev
notifications:
  email:
    recipients:
      - d.rubio@outlook.com
services:
  - mongodb

script:
  #- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=daniel-nx -Dsonar.login=$SONAR