language: java

#jdk:
#  - oraclejdk8

#dist: trusty

branches:
  only:
    - master
    - "/^release-[0-999].[0-999]$/"
    - develop

notifications:
  email:
    recipients:
      - d.rubio@outlook.com

script:
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=daniel-nx -Dsonar.login=$SONAR

deploy:
  provider: heroku
  on:
    branch: develop
  app: nx-ese-spring
  api_key:
    secure: R+OwIhrAbY3BSYLRsKd1zaGlOpHZgYx/y6WbpCkvDvVDpmQqlI6RnN1DdvwZLOK2Wgc6keHaAk4f35JrdNRbHvI26amwV/cjyaqj6dTwnQ4C+jnwAH9dW42CCLihmWhbdaMt0tOuN3kEClagILw0SdL5/h5PocFGXUIVAHv2pd8MKm1HhAqTyZkWaIFQu8HtNGlio4xKrvSmzxsiWxeHELvHUwxBJyfizU2g74ywnKLDoCAgPGM1tF+g9X3MypeTbZ2APPiYVs7K2r3P6Q0ZIOC70yRqHaIM/9PavF+QUzl8TshzMh5HeWjEucw3u9DZhDVRiGt5U4MtUVx/Ueas0J758p/5gbKgbYdrvIzKr2+Tp3pFZHm5ydBH3EJ09Zo0dvDwWDmiRsE7SZ4STug6MYpDBkQgmJnjXiV1PfzZUlrmX+3Szv+6EIkuPdBzqeiAWtFobgO0AuldsOPFKwRCUxewze2bjdyFBP4geYkUhHZGf7yC8h3syW6jw9nfqyggH7Nm5vldisAAmxLW77asRRn5ZpingQDkpoOdGiuYHIt6vGqvWda89ZH2Kn6rQStX7HtUYPUL4d9kVKV7Y9YMHtVgnmxGleHzM5BN5szJ9uJaXLil07k9MIYfosLFcGhW5MAkvAo0MFR6oU5U8Pc2Gq7Spl52oRbOJWC5Buja1G8=

env:
  secure: Bh3pvDKQOsWV5Fx2DUHGg3S6AXyIer6U0WpCPJkMAplw1FHbKcRUmxaaowu0DDGyQylfuSxXmOH+n9ZATYVgzv3ifbUle5zXOcyjC7pdBewqyVST/XAAsFW2lCTbiq0wsLaeg0wqu7El9KPfMOHEfeQ6
    bODjzlb0wESPBArgP9fepfOxpgMme6Mnh5ZrbDlwPhj2hbd8jX0nkbj2qhgM1cDhm1BjCja8wGFvJH74ZOstWeUjU4AJuQ5cWGAss4ERrtL0az8XgcafbTT0ZiKzl9+lAmk05XzbrxrhdKLxaI3luf5AYepvHTOaS8+
    eK7W0bxT4lGQM2ESaNVHhQG0u3cK9rZvnTGdeYW5xcCq2LAH9mcAFUiPLthMXKZgRmQljkcIgFbQ/FKMbwJvb1BUujqd0w7veaet/Ql1mRRcqzxPEPrnIQEcm/Jz1TSppSG4zFrocVyTOwSNUQbMkPJueZR4cd7KTRX
    eRSktL+qkxK0g/15DamyQJqe+oWoBzsUI7wW796a2/2RrlxWBKfPL1WVtK1v3jx2zA/qHvNc5uA8hT0uojI/ZfzOrGcWf0zS2ndB/HvvxTYV465RGqcr4aMw1Nae78UQtcYWSugV/vmW93XAe8ryZ77OYT9VOWKHAWU
    3qYH9DVaGUb5e5UFZobXrBIkDTUt+Qx/24/JK7t/Ag=

