language: java
jdk:
  - oraclejdk8
dist: trusty
branches:
  only:
    - master
    - dev
notifications:
  email:
    recipients:
      - d.rubio@outlook.com
services:
  - mongodb

script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify